### ISSUE TITLE
crew planning - AttributeError: 'TaskOutput' object has no attribute 'list_of_plans_per_task'

### ISSUE THREAD

**Issue by strnad** [crewAIInc/crewAI#968]
When i set the planning of crew to true, it throws following exception:
```
"Traceback (most recent call last):
  File "/home/jakub/newai/CrewAI-Studio/app/pg_crew_run.py", line 53, in run_crew
    result = crewai_crew.kickoff(inputs=inputs)
  File "/home/jakub/newai/CrewAI-Studio/venv/lib/python3.10/site-packages/crewai/crew.py", line 463, in kickoff
    self._handle_crew_planning()
  File "/home/jakub/newai/CrewAI-Studio/venv/lib/python3.10/site-packages/crewai/crew.py", line 564, in _handle_crew_planning
    for task, step_plan in zip(self.tasks, result.list_of_plans_per_task):
  File "/home/jakub/newai/CrewAI-Studio/venv/lib/python3.10/site-packages/pydantic/main.py", line 828, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'TaskOutput' object has no attribute 'list_of_plans_per_task'
```

**Comment by EasonHuangkkq** [comment]
`    
    def _handle_crew_planning(self):
        """Handles the Crew planning."""
        self._logger.log("info", "Planning the crew execution")
        result = CrewPlanner(self.tasks)._handle_crew_planning()
        print("result", result.pydantic)
        # for task, step_plan in zip(self.tasks, result.list_of_plans_per_task):
        #     task.description += step_plan
        for task, step_plan in zip(self.tasks, result.pydantic.list_of_plans_per_task):
            task.description += step_plan
            `
    in crew.py, i change to  result.pydantic.list_of_plans_per_task.
    it works for me

**Comment by strnad** [comment]
fixed by https://github.com/crewAIInc/crewAI/pull/969/

**Comment by MohamedAziz24** [comment]
I have same issue when using guardrails

	`
def validate_json_output(result: str) -> Tuple[bool,Any]:
	"""Validate that the output is valid JSON."""
	try:
		json_data = json.load(result)
		return (True, json_data)
	except json.JSONDecodeError:
		return (False, "Output must be valid JSON")
	` 
The above solution does not solve
How to fix this?

**Comment by Vidit-Ostwal** [comment]
@MohamedAziz24, just checking in, are you using the latest crewai version
You can update it by `pip install -upgrade crewai`
